### PR TITLE
Support different fonts for text segment

### PR DESCRIPTION
**Pull request by vpetrykov**
### **Context**
As described in https://github.com/nedap/segnify-ios/issues/12#issue-386476521 we want the UI to reflect with a bold styling on a text when it’s selected. 
At this moment, for both cases when a text is(not) selected we display text similarly

### **Relevant issue**
- #12 

### **Changes**
- making a font styling of the `TextSegment` depending on the state

**Known problems**
- What problems do still arise or are anticipated?
- Which part of the solution do you need help with?

**Extra attention**
- What do I need to pay extra attention to as a reviewer?

**Check-list**
- [ ] Acceptance criteria described in the issue are satisfied, or the bug(s) is/are fixed.
- [ ] Documentation present (relevant information is properly documented).
- [ ] Written tests for test suite (optional).
- [X] CHANGELOG updated.

**Tested on devices**
- [ ] Minimum supported iOS version.
- [ ] Maximum supported iOS version.
- [ ] Lowest resolution supported.
- [ ] Highest resolution supported.
- [ ] Device with a notch.

**Is this issue considered as Done?**
- [ ] It meets our [DoD](https://github.com/nedap/healthcare-mobile/wiki/DoD).

### CODE REVIEW

**Review by dregatos — CHANGES_REQUESTED** [review]
Hey @vpetrykov,

Thank you for taking care of this issue. The changes look OK but it would be great if you update our demo app (the one inside of the `iOS Example` folder), so the changes can be really tested and (related to your question) will have an example of how to adapt Ons Dossier to this new version...it's the only app using this framework :)

**Comment by vpetrykov** [comment]
@dregatos here're two commits
- https://github.com/nedap/segnify-ios/pull/56/commits/3c238fcaf109fc28edef9c153e17f1ff03521014 Minimal required change for the Dossier after the bump
- https://github.com/nedap/segnify-ios/pull/56/commits/1653c7720c282ea143737ceb774d45e661cf515e An example of using a button with a text segment configurations

**Comment by dregatos** [comment]
@vpetrykov does the demo app work on your machine? I'm still not able to test the changes :(


image_name

**Comment by dregatos** [comment]
@vpetrykov I have fixed the demo app execution in this [commit](https://github.com/nedap/segnify-ios/pull/56/commits/76ee3c4fe44930d90036eeaf5fbb03f722a715ea) and tested the changes by integrating the local version in Ons Dossier project (i.e. drag&dropping the local folder of the package into the app project)

image_name

I have also adapted the `TextSegmentConfigurator` like this

image_name

and it seems that the font is not really changing when selecting a tab...

image_name

Did I miss something?

**Comment by vpetrykov** [comment]
@dregatos sorry for the confusion. You've applied changes correctly in Dossier. The previous implementation of this PR applied bold text styling for all instances initialized using textSegmentConfigurators. It shouldn't be the case with an update in the recent commit https://github.com/nedap/segnify-ios/pull/56/commits/23599a7b377ac6d5be39887082952af5c40458e8

Mostly, the visual difference between `.selectedSegmentedControl` and `.deselectedSegmentedControl` UIFonts is undetectable, but you can still see it when clicking tabs on Profile or Episodes pages. The reason is in styling we are applying it in the Dossier repo (_where it's set_)
- https://github.com/nedap/dossier-ios/blob/develop/Dossier/Styles/Fonts.swift#L22
- https://github.com/nedap/dossier-ios/blob/develop/Dossier/Styles/Fonts.swift#L23

**Review by dregatos — CHANGES_REQUESTED** [review]
@vpetrykov,

Know it works great in Ons Dossier 🥳


https://github.com/nedap/segnify-ios/assets/4560667/4be8ce80-507e-4889-886c-0c09ef6e2972

Could you please fix the demo app and also make it behave in a similar way so we have an example of how to use it here?

image_name

**Comment by vpetrykov** [comment]
referencing newly created issue in Dossier
- https://github.com/nedap/dossier-ios/issues/2139

**Review by dregatos — APPROVED** [review]
Great job @vpetrykov. Thank you for making segnify prettier 🤩

Alt Text

**Pull request merged**
